### ISSUE TITLE
Thumbnail is null

### ISSUE THREAD

**Issue by squareborg** [ramsaylanier/wordexpress-schema#27]
Hi It seems that I cannot access the thumbnail for any posts. They always come up null. The posts do have postmeta of _thumbnail_id. Any ideas? 

PS thanks for this cool project

![image](https://user-images.githubusercontent.com/8677881/53432599-ba2aac00-39ea-11e9-9c11-0eb7dad8dc8b.png)

**Comment by ramsaylanier** [comment]
@stedotmartin Thanks for filing an issue. I'll take a look at this soon. Do you happen to have a repo with a reproduction of the issue?

**Comment by squareborg** [comment]
Grrr, sorry I just seen that I had `amazonS3: true` in the config I set this false and now I am getting thumbnails back. Sorry must of copied pasted some config from the initial install.
