### ISSUE TITLE
Advantage of using Sequalize vs wrapping the REST API

### ISSUE THREAD

**Issue by BLamy** [ramsaylanier/wordexpress-schema#5]
Is there any advantage to using direct SQL vs going through the REST API? 

Pros of wrapping REST
- Permissions for free
- Possibility generate graphQL from the REST API see [WPAPI-SwaggerGenerator](https://github.com/starfishmod/WPAPI-SwaggerGenerator)

Rest Library 
http://v2.wp-api.org/reference/posts/

Possible Libraries
https://github.com/facebook/dataloader
https://github.com/Automattic/wpcom.js

**Comment by ramsaylanier** [comment]
When I first started this, the WordPress API only had a some basic REST endpoints, which meant having to write custom endpoints to get data I wanted. When I looked into doing that, I realized that doing so required me to sometimes get overlapping data. I figured it was better to use Sequelize to, essentially, write my own API. Basically, using Sequelize gives me more control over what I'm asking for. Furthermore, it allows me to shape the returned data how I see fit. My last concern would be having to re-write GraphQL schemas if the structure of the WordPress API changes.

That being said, its probably more work than wrapping the existing API. There really should be no reason you couldn't.
