### ISSUE TITLE
What about ACF?

### ISSUE THREAD

**Issue by josephdburdick** [ramsaylanier/wordexpress-schema#9]
Hi @ramsaylanier, I think this is an appropriate question to ask: what about ACF? Certainly most people who are using Wordpress as a serious CMS is using Advanced Custom Fields so the admin can generate content for multiple pages, multiple templates. If the Wordpress page is defined in the schema but the ACF can change template to template, how does one go about defining each one? Would you customize using "fragments"? If you could point me in the right direction I'd be very grateful, thanks!

**Comment by ramsaylanier** [comment]
So, I've used ACF with this project, specifically for the layout. You just need to setup what is called in GraphQL land a "connector", which is a way to connect the GraphQL server to your database. [This is the reference for the getPostLayout connector](https://github.com/ramsaylanier/WordExpressSchema/blob/master/src/db.js#L207-L214). 

Postmeta is a defined model using Sequelize. It simply maps to the MySQL postmeta table. By creating this model, you can then query the database, which is what `getPostLayout` is doing. It does require that you know how ACF is storing the field in the database, though. Should be pretty easy to figure out with any sort of SQL client (I personally use Sequel Pro).

**Comment by josephdburdick** [comment]
Thank you for the explanation, it helped guide me in the right direction.

**Comment by joernroeder** [comment]
@josephdburdick starting with ACF and WordExpressSchema too. could you share how you resolved addtional fields by type? I'm usually creating a custom post type similar to http://blog.teamtreehouse.com/adding-custom-fields-to-a-custom-post-type-the-right-way and enhancing it with custom fields.
thanks in advance!

**Comment by ramsaylanier** [comment]
@josephdburdick can you create a separate issue for this and also provide a more detailed explanation of what you are trying to accomplish and I'll try and help you out!
